URL_SERVICE = "https://cnt-2801ea26-f634-4c7b-ad14-aeb6b30daf24.containerhub.tripleten-services.com/"
DOC_PATH = "/docs/"
LOG_MAIN_PATH = "/api/logs/main/"
USERS_TABLE_PATH = "/api/db/resources/user_model.csv"
CREATE_USER_PATH = "/api/v1/users/"
PRODUCTS_KITS_PATH = "/api/v1/products/kits/"
KITS_PATH = "/api/v1/kits"